# Generated by Django 4.1.4 on 2022-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hazards",
            fields=[
                (
                    "sLocationName",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("sPhenomena", models.CharField(max_length=8, null=True)),
                ("sStartTime", models.DateTimeField(null=True)),
                ("SEndTime", models.DateTimeField(null=True)),
            ],
        ),
    ]
