# Generated by Django 4.1.4 on 2023-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hazards",
            fields=[
                (
                    "sLocationName",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("sPhenomena", models.CharField(max_length=15, null=True)),
                ("sStartTime", models.DateTimeField(null=True)),
                ("sEndTime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="rain",
            fields=[
                (
                    "sCity",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("sRAIN", models.FloatField()),
                ("sMIN_10", models.FloatField()),
                ("sHOUR_3", models.FloatField()),
                ("sHOUR_6", models.FloatField()),
                ("sHOUR_12", models.FloatField()),
                ("sHOUR_24", models.FloatField()),
                ("sNOW", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="rain_pop",
            fields=[
                (
                    "sLocationName",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("sPop", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="weather_forecast",
            fields=[
                (
                    "sLocationName",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("sWx", models.CharField(max_length=15, null=True)),
                ("sMinT", models.FloatField()),
                ("sMaxT", models.FloatField()),
                ("sCI", models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
