# Generated by Django 4.1.4 on 2022-12-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CWBdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hazards",
            old_name="SEndTime",
            new_name="sEndTime",
        ),
    ]
