# Generated by Django 4.1.4 on 2022-12-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CWBdata", "0002_rename_sendtime_hazards_sendtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazards",
            name="sEndTime",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="hazards",
            name="sStartTime",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
