# Generated by Django 4.1.4 on 2022-12-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CWBdata", "0003_alter_hazards_sendtime_alter_hazards_sstarttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazards",
            name="sPhenomena",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
