# Generated by Django 4.1.4 on 2022-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CWBdata", "0005_alter_hazards_sendtime_alter_hazards_sstarttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazards",
            name="sEndTime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="hazards",
            name="sStartTime",
            field=models.DateTimeField(null=True),
        ),
    ]
