# Generated by Django 4.1.4 on 2022-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CWBdata", "0006_alter_hazards_sendtime_alter_hazards_sstarttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="rain",
            fields=[
                (
                    "sCity",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("sRAIN", models.FloatField()),
                ("sMIN_10", models.FloatField()),
                ("sHOUR_3", models.FloatField()),
                ("sHOUR_6", models.FloatField()),
                ("sHOUR_12", models.FloatField()),
                ("sHOUR_24", models.FloatField()),
                ("sNOW", models.FloatField()),
            ],
        ),
    ]
