# Generated by Django 3.2.5 on 2022-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0008_weather_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='river',
            fields=[
                ('sStationID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sStationName', models.CharField(max_length=15, null=True)),
                ('sRiverName', models.CharField(max_length=15, null=True)),
                ('sLocationAddress', models.CharField(max_length=50, null=True)),
                ('sStationStatus', models.CharField(max_length=15, null=True)),
                ('sAlert1', models.FloatField()),
                ('sAlert2', models.FloatField()),
                ('sAlert3', models.FloatField()),
                ('sWaterLevel', models.FloatField()),
            ],
        ),
    ]
