# Generated by Django 3.2.5 on 2022-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0010_auto_20221228_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='sAlert1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='sAlert2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='sAlert3',
            field=models.FloatField(null=True),
        ),
    ]
