# Generated by Django 3.2.5 on 2022-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0011_auto_20221228_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='sAlert1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='sAlert2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='sAlert3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='sRecordTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='river',
            name='sWaterLevel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
