# Generated by Django 3.2.5 on 2022-12-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0012_auto_20221228_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='sAlert1',
        ),
        migrations.RemoveField(
            model_name='river',
            name='sAlert2',
        ),
        migrations.RemoveField(
            model_name='river',
            name='sAlert3',
        ),
    ]
