# Generated by Django 3.2.5 on 2022-12-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0013_auto_20221228_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='river',
        ),
    ]
