# Generated by Django 3.2.5 on 2022-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0014_delete_river'),
    ]

    operations = [
        migrations.CreateModel(
            name='flooded',
            fields=[
                ('sStationId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sStationName', models.CharField(max_length=15, null=True)),
                ('sCountyName', models.CharField(max_length=15, null=True)),
                ('sTownName', models.CharField(max_length=15, null=True)),
                ('sValue', models.FloatField()),
            ],
        ),
    ]
