# Generated by Django 3.2.5 on 2022-12-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0015_flooded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flooded',
        ),
        migrations.RemoveField(
            model_name='weather_forecast',
            name='sPop',
        ),
    ]
