# Generated by Django 3.2.5 on 2022-12-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBdata', '0016_auto_20221229_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='rain_pop',
            fields=[
                ('sLocationName', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sPop', models.FloatField()),
            ],
        ),
    ]
