# Generated by Django 4.1.4 on 2022-12-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="lineUser",
            fields=[
                (
                    "sLineID",
                    models.CharField(max_length=33, primary_key=True, serialize=False),
                ),
                ("sName", models.CharField(blank=True, max_length=20)),
                ("sCity", models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
