# Generated by Django 4.1.4 on 2023-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="lineUser",
            fields=[
                (
                    "sLineID",
                    models.CharField(max_length=33, primary_key=True, serialize=False),
                ),
                ("sName", models.CharField(max_length=20, null=True)),
                ("sCity", models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
