# Generated by Django 4.1.4 on 2022-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatGPT", "0002_lineusermain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineuser",
            name="sCity",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name="lineUserMain",
        ),
    ]
