# Generated by Django 4.1.4 on 2022-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatGPT", "0003_alter_lineuser_scity_delete_lineusermain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineuser",
            name="sCity",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
