# Generated by Django 4.1.4 on 2022-12-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatGPT", "0004_alter_lineuser_scity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineuser",
            name="sCity",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="lineuser",
            name="sName",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
